package com.wipro.candidate.dao;

import com.wipro.candidate.bean.CandidateBean;
import com.wipro.candidate.util.DBUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

public class CandidateDAO {
    
    
   
    public String addCandidate(CandidateBean candidateBean) {
        Connection conn = null;
        PreparedStatement pstmt = null;
        
        try {
            conn = DBUtil.getDBConn();
            
            if (conn == null) {
                return "FAIL";
            }
            
            String sql = "INSERT INTO CANDIDATE_TBL (ID, NAME, M1, M2, M3, RESULT, GRADE) VALUES (?, ?, ?, ?, ?, ?, ?)";
            pstmt = conn.prepareStatement(sql);
            
            pstmt.setString(1, candidateBean.getId());
            pstmt.setString(2, candidateBean.getName());
            pstmt.setInt(3, candidateBean.getM1());
            pstmt.setInt(4, candidateBean.getM2());
            pstmt.setInt(5, candidateBean.getM3());
            pstmt.setString(6, candidateBean.getResult());
            pstmt.setString(7, candidateBean.getGrade());
            
            int rowsInserted = pstmt.executeUpdate();
            
            if (rowsInserted > 0) {
                return "SUCCESS";
            } else {
                return "FAIL";
            }
            
        } catch (SQLException e) {
            e.printStackTrace();
            return "FAIL";
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
   
    public ArrayList<CandidateBean> getByResult(String criteria) {
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        ArrayList<CandidateBean> candidateList = new ArrayList<>();
        
        try {
            conn = DBUtil.getDBConn();
            
            if (conn == null) {
                return null;
            }
            
            String sql;
            
            if (criteria.equalsIgnoreCase("PASS")) {
                sql = "SELECT * FROM CANDIDATE_TBL WHERE RESULT = 'PASS'";
                pstmt = conn.prepareStatement(sql);
            } else if (criteria.equalsIgnoreCase("FAIL")) {
                sql = "SELECT * FROM CANDIDATE_TBL WHERE RESULT = 'FAIL'";
                pstmt = conn.prepareStatement(sql);
            } else if (criteria.equalsIgnoreCase("ALL")) {
                sql = "SELECT * FROM CANDIDATE_TBL";
                pstmt = conn.prepareStatement(sql);
            } else {
            	return null;
            }
            
            rs = pstmt.executeQuery();
            
            while (rs.next()) {
                CandidateBean candidate = new CandidateBean();
                candidate.setId(rs.getString("ID"));
                candidate.setName(rs.getString("NAME"));
                candidate.setM1(rs.getInt("M1"));
                candidate.setM2(rs.getInt("M2"));
                candidate.setM3(rs.getInt("M3"));
                candidate.setResult(rs.getString("RESULT"));
                candidate.setGrade(rs.getString("GRADE"));
                candidateList.add(candidate);
            }
            
            if (candidateList.isEmpty()) {
                return null;
            }
            
            return candidateList;
            
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    /**
     * This method should contain the necessary code to create a new Candidate id.
     * CandidateID is a combination of first 2 letters of name in uppercase
     * followed by 4 digit number that will be generated by the sequence.
     * For eg, the Candidate id for a Candidate Jacob could be JA5000
     * The function should return the generated Candidate id.
     * 
     * @param name - Candidate name
     * @return Generated candidate ID
     */
    public String generateCandidateId(String name) {
        Connection conn = null;
        PreparedStatement pstmt = null;
        PreparedStatement pstmtUpdate = null;
        ResultSet rs = null;
        String candidateId = null;
        
        try {
            conn = DBUtil.getDBConn();
            
            if (conn == null) {
                return null;
            }
            
            // Get the current sequence value and increment it
            String selectSql = "SELECT seq_value FROM CANDID_SEQ WHERE seq_name = 'CANDID_SEQ'";
            pstmt = conn.prepareStatement(selectSql);
            rs = pstmt.executeQuery();
            
            int seqValue = 5000; // Default start value
            
            if (rs.next()) {
                seqValue = rs.getInt("seq_value");
            }
            
            // Update the sequence value for next use
            String updateSql = "UPDATE CANDID_SEQ SET seq_value = seq_value + 1 WHERE seq_name = 'CANDID_SEQ'";
            pstmtUpdate = conn.prepareStatement(updateSql);
            pstmtUpdate.executeUpdate();
            
            // Extract first 2 letters of name in uppercase
            String prefix = name.substring(0, 2).toUpperCase();
            // Create candidate ID
            candidateId = prefix + seqValue;
            
            return candidateId;
            
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (pstmtUpdate != null) pstmtUpdate.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
            